[Deploy]

diff --git a/.github/workflows/shorebird_android_version_01.yml b/.github/workflows/shorebird_android_version_01.yml
--- a/.github/workflows/shorebird_android_version_01.yml
+++ b/.github/workflows/shorebird_android_version_01.yml
@@ -25,14 +25,22 @@ jobs:
         
       - name: 🚀 Shorebird Release
         if: ${{ github.event.created }}
-        uses: shorebirdtech/shorebird-release@v0
-        with:
-          platform: android
+        run: |
+          shorebird release android --flutter-version=3.19.6 | tee output.log
+          GREP_MATCH=$(grep -Ei "Published Release (.*)" output.log)
+          if [[ $GREP_MATCH ]]; then
+            # Strip the non-version-number characters from the line
+            RELEASE_VERSION=$(echo $GREP_MATCH | sed -E 's/^.+ Published Release (.*)\!$/\1/')
+            echo "release-version=$(echo $RELEASE_VERSION)" >> $GITHUB_OUTPUT
+          else
+            echo "Failed to create release"
+            exit 1
+          fi
 
       - name: 🚀 Shorebird Patch
         if: ${{ !github.event.created }}
         run: |
-          shorebird patch android --release-version=1.2.3+4 | tee output.log
+          shorebird patch android | tee output.log
           GREP_MATCH=$(grep -Ei "Published Patch (.*)" output.log)
           if [[ $GREP_MATCH ]]; then
             # Strip the non-version-number characters from the line
